#!/bin/bash

# The MIT License (MIT)
# Copyright (c) 2013 Alvin Abad
# https://alvinabad.wordpress.com/2013/03/23/how-to-specify-an-ssh-key-file-with-the-git-command

# remove temporary file on exit
# trap 'rm -f /tmp/.git_ssh.$$' 0
rm -f /tmp/.git_ssh.*


SSH_KEY=""

if [ -f "$GIT_SSH_KEY" ]; then
  SSH_KEY=$GIT_SSH_KEY
fi

if [ -f "../id_rsa" ]; then
  SSH_KEY="../id_rsa"
fi

if [ -f "./id_rsa" ]; then
  SSH_KEY="./id_rsa"
fi

if [ "$1" = "-i" ]; then
    SSH_KEY=$2; shift; shift
fi


if [ ! -z $SSH_KEY ]; then
    echo "ssh -i $SSH_KEY \$@" > /tmp/.git_ssh.$$
    chmod +x /tmp/.git_ssh.$$
    export GIT_SSH=/tmp/.git_ssh.$$
fi

# in case the git command is repeated
[ "$1" = "git" ] && shift

git $@
